spring:
  datasource:
    url: jdbc:mysql://google/reactlibrarydatabase?cloudSqlInstance=inlaid-micron-435801-j1:us-central1:reactlibrarydatabase&socketFactory=com.google.cloud.sql.mysql.SocketFactory
    username: <username>
    password: <Password>
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    sql:
      init:
        mode: always
  data:
    rest:
      base-path: '/api'