spring:
  datasource:
    url: jdbc:mysql://${RDS_HOSTNAME:localhost}:${RDS_PORT:3306}/${RDS_DB_NAME:reactlibrarydatabase}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    sql:
      init:
        mode: always
  data:
    rest:
      base-path: '/api'

okta:
  oauth2:
    client-id: ${OKTA_CLIENTID}
    issuer: ${OKTA_ISSUER}

server:
  port: '8081'
  ssl:
    enabled: true
    key-alias: 'luv2code'
    key-store: 'classpath:luv2code-keystore.p12'
    key-store-password: 'secret'
    key-store-type: 'PKCS12'

stripe:
  key:
    secret: ${STRIPE_SECRET}